#!/bin/bash
# credit https://github.com/jerboaa from https://github.com/fabric8io-images/maven-builder/blob/d81dedbc298dee7e071ac2bc1e0050ae7ee1e5aa/set_java

ARCH=$(uname -m)
echo $ARCH

if [[ ${ARCH} == 'x86_64' ]]; then
  JAVA_32=$(update-alternatives --display java | grep family | grep i386 | cut -d' ' -f1)
  if [[ -n "${JAVA_32}" ]]; then
    update-alternatives --set java ${JAVA_32}
  else
    echo "No 32-bit Java alternative found."
  fi

  # Maven actually uses javac, not java
  JAVAC_32=$(update-alternatives --display javac | grep family | grep i386 | cut -d' ' -f1)
  if [[ -n "${JAVAC_32}" ]]; then
    update-alternatives --set javac ${JAVAC_32}
  else
    echo "No 32-bit Javac alternative found."
  fi
  exit $?
fi