FROM --platform=$BUILDPLATFORM golang:1.22.2 AS build

ENV GO111MODULE=on
WORKDIR /app
COPY ./tools ./tools
COPY go.mod go.sum ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -o docker-build ./tools/docker-build

FROM centos:7

# CentOS 7 is EOL, replace the mirror
RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo && \
    sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo && \
    sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo && \
    echo "sslverify=false" >> /etc/yum.conf && \
    yum makecache

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV PATH=/opt/sonar-scanner/bin:$PATH
# for ansible
ENV PATH=$PATH:/root/.local/bin
ENV PATH=$PATH:/usr/local/bin

COPY jenkins-agent/base/ ./

RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y ansible && \
    pwd && ls -a && \
    ansible-playbook ./ansible/playbooks/main.yaml -vvv -e required=true -e distribution=centos

RUN chmod +x ./hack/install_qemu.sh && ./hack/install_qemu.sh

# https://github.com/CentOS/sig-cloud-instance-images/issues/71
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# USER jenkins
# WORKDIR /home/jenkins

COPY --from=build /app/docker-build  /bin/

CMD ["docker","version"]